### ISSUE TITLE
Google Pay ERROR

### ISSUE THREAD

**Issue by danneljt2020** [wl-online-payments-direct/sdk-php#11]
I am testing in DEV the integration with Google Pay through the PHP SDK, and the payment request is failing due to some incorrect value. Could you please review the data I’m sending to see if I’m missing something?

REQUEST:
![Request GPay Error](https://github.com/user-attachments/assets/e9460d74-ec79-43e1-9b03-e224ac811676)

RESPONSE:
![GPay error Response](https://github.com/user-attachments/assets/d0ef5d2e-6f51-4653-b072-c015adaf210e)

REQUEST JSON:
{
   "mobilePaymentMethodSpecificInput":{
      "authorizationMode":"SALE",
      "encryptedPaymentData":"{\"signature\":\"eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIiLCJraWQiOiJiMzUyM2IyZS1jMzI0LTQzMWUtYjVhYi1kMGU5MzIwZGRhMzIifQ.KfVwbwEVYg6KcFpQjZ67PLHA2JYiuyqHasYZvYJ_jGGYuRYGR4TTkF0aKE2CfuPzm5Z_IK1fH3pS7qqPY6sOxd2jMeaC8e7HFYRW2gY32lbn6nBouh--OrWo6kaK83TFhoDAO1XUzQQWiZGIo8pxK2t3IzG7NZlTwlaQyPNsxPY4wc_lxYUg5wlBZu17RyaBEo4716jdDYo1ED0we8-xl7_rrdbQrrKmJbzfSJHUero69QdzoSVZnqjgEh8mGp5Fsm_fuc3LQjywpvQWprsA1uFgq11iBe7ZwOxLV8sKIHfIlCqgbD42t_4couZDLH-NmfSWZeEHtZF88ptLKyqDGg.Pd0xZJk9KuSMmm-WR-jChg.C6Sk8d2vDtNIKFtbSg75GysP9kUN69LPM5NvtWcCiir41E0WZP_as5cQY9KJF4ejkNPg9R0LTJdP7mOtYYetM_b3BoZ5TdyPLYJNz8e34IqEf5MACF5FClAvJZ3Da-rETE15D-91CoqxSHygyXcoZLuY-uokJ6h5jrheQrirUr2J_B9DvUC7El4xPTBZJQ3YLXlNa4o5_l206NtErGqBxaVVWnTMMWACNCMdDQ1MMKBZ64HoT5SCwsPl2QUks2kuPSZNZJkAOoSqRVaz8dYxUZ2pU8rhqKJynmffSyWJc5ynykxYxX4d_a5D1zn1o_AM3dj5pZkgAZyJDcH_snyLlUXBCFXhRh9WZzP7zTY7OxHIw4brDn3JdxSDwrl_Mydy32ONnXI1zcU_XmyAcN7IGtzazVy0ReXJHPkzj5N_C8GQf4z4VwPOXNwa3NGPLvws5eY3Wp2fooDS1-wRpT5ii6Vg7K0xZBgUaBNBbNVyEK0kExZYBOgU19ipTAeZTTBFC7QHvF7dIq-AZsqwohSHmxgSYlp4JEN-xwe5To9vFAb-0a-ISt6Hy7AunyxZbvT707p5hso8w_9GXtWcLRO2MbBsamrqav8H2Wc5I31NXe8ftSssKl3Yk41TrtBpDmpjRvVhSgR3iPi3O3Yup3ELeO4rw8GwlInO4uR4OsgALIOtyVTubffTxmOmPGB_hVOoiFqeq3oeG27cNQ-8FyWBfceafBnrETrJowTztcUKBarmCSe3yIdtDyzmSVuQW9_rRAEzM5bHQucYEQgN7y87hzw07w2lqw6_oFy5iggfOReJJ9-7G0kQRyqJRmqG8S6EDJXXHAAupPd-tFXMgksGkTsXhFc7tv6OuoZdt3pDVfT1LiMe_e1HV4G4eO6usPIDcgfIWUyT5Wj9aGSA0pesBA1YYgqp8EBJp9m5aUOA9kdr738hjk_ODZoAjrPga2L_faCHVbv-loznFypA1tr-4odlAAJly_pzLlG3sP6KenlR8tbZcSuH8Ve9HgpJ1n5yOixn3Wg1QiBATmYavUReAcWfHuxMdGEI5mBnXHUku5XdvxrtKvSgMTHdGzVtjZ_u9jNCE2r7zl0RAFUEqA17gLODZGdfMLDfSALmGQV8ulEVVwujTd1lkG4-DkL8Dq21GfBBXmaLJ0aAuZEaU4H-oM1V9jb-g-ZBTlvY_BmSb7nUv2nN5wqmXie1lEcfomzkLwhQ5molnUYP2I5KHavg8eYWWYKv3isost7pAaFfYZqEWh3i-_a9T8b2CU4JbETEfxaVd0-KaXtve42bBguwjoKT3wY99v8Iv7eKeDWL8Qh6Va0M_E-ZiucTTwkjQQxGV6aUQSd4p099c8ZVcRPHtHsr6kO9IlWCMBSEnir7QjQPBdX7YFvneb3e_g3xjJiunhq0GVkLqRjWJdBtpj_3UE7zc5b1xIA7QzoWWDw-2lN1pVPqQUtTdy_OWING4ILptezqh4-3PYlWZ9JmQSS6Y4sw54bPHCcZNofkd6wVnUp28TPHt2exzdKO9oAp4F4funk5VzpFzuILbfhnMCD54SBwaDRf24r6sIOo0fBjX1ae2r7ZSb4DmjgfbWV8dTWTg8TmJD7ONXz5x-yXVgFMb_urMh7DGZnQu5X3pdMwCG9Cw_v0dpOjJ3yumvu2GEqR34w0VRzgtENeufC7dQDl_wF8xnrv0xxnZCe_eznkmh7OUpgqW76HnCiMbfLsThQpAUvP0bcr5edA7w7jIOITkb-DYGNHyfzw1csVW-M4bkGo2TIWStV2P5UBzYVJiFWktHDjQM2J0dawPh0zBAcnEsgyTlRANMVhky-HoClKExwAs4nkOVrIH2mCGDuowaFvxd9pSCWN2OJHFJf6Y5cUju3kxydt3A947VBG8-5EeL6pSmfTe16Nr8BYrDbVJ6MFWOtBY1ZZcFIHZx2GdM7Q4F2XkegahL8RxbTh7tt9yGYiIKPtIi3KqudSgTPzffgXzqebh_3oT2F3UZrNkyZomYSZWgF47s5R5ZbiwAYqoW_ljMUskqMIHngyQ0zBP3NVdONWmtBdgwtdoNxWbarLF3DuBBx9FugIU6XOHiJcAHl4Bk-e2xdlY6TxR1JbJYk1WKdzsfpsQpeCExmLznZ0Kdqj2YXlu1Gzy0qFd7QQydfnsXS7o1hSV41s-5dpdWWb.at2cABJa461lWQSaJbJNNLFlRbmy5fCLlbgB5vDtdZ4\"}",
      "paymentProduct320SpecificInput":{
         "threeDSecure":{
            "challengeCanvasSize":"600x400",
            "challengeIndicator":"no-preference",
            "redirectionData":{
               "returnUrl":"https://domain.com/callback-url"
            },
            "skipAuthentication":false
         }
      },
      "paymentProductId":320,
      "requiresApproval":true
   },
   "order":{
      "amountOfMoney":{
         "amount":"1000",
         "currencyCode":"EUR"
      },
      "customer":{
         "billingAddress":{
            "countryCode":"ES"
         },
         "contactDetails":{
            "emailAddress":"user@domain.com",
            "faxNumber":"9103000003225247",
            "phoneNumber":"+34-666666666"
         },
         "device":{
            "acceptHeader":"*\/*",
            "browserData":{
               "colorDepth":"24",
               "javaEnabled":true,
               "javaScriptEnabled":true,
               "screenHeight":1080,
               "screenWidth":1920
            },
            "ipAddress":"127.0.0.1",
            "locale":"es",
            "timezoneOffsetUtcMinutes":180,
            "userAgent":"userAgent"
         },
         "fiscalNumber":"44444444Y",
         "locale":"es",
         "merchantCustomerId":"9103000003225247"
      },
      "references":{
         "descriptor":"Client App",
         "merchantReference":"800074833172432093144"
      }
   }
}

Thanks!

**Comment by worldline-direct-support-team** [comment]
Hello @danneljt2020,

Thank you for reaching out to us and sharing the information regarding the issue you are facing. We appreciate your diligence in bringing this to our attention.

Upon further investigation, it appears that the issue you are encountering is related to the API rather than the SDK itself. To ensure you receive the best possible support for this issue, we kindly suggest submitting a request through our [Contact Form](https://docs.direct.worldline-solutions.com/en/about/contact/) on our Documentation portal. Our support team is readily available to assist you in resolving the issue and answer any questions you may have specifically related to the API.

If you encounter any issues specifically related to the SDK, we are more than happy to provide you with assistance as well. We appreciate your feedback and apologise for any inconvenience this issue may have caused.

Kind regards,
Worldline Online Payments Support
