### ISSUE TITLE
create HostedCheckout auto detect card type

### ISSUE THREAD

**Issue by mabaied** [wl-online-payments-direct/sdk-php#3]
Hello, 
How to create HostedCheckout auto detect card type without select type (for example, without select VISA or PayPal), when I put card number,  detects automatically card type?

**Comment by worldline-direct-support-team** [comment]
Hi Mabaied,

It looks like you're looking for a specific Direct feature. This space is aimed at helping with issues found with the SDK.

Information on the feature can be found on the [support portal](https://support.direct.ingenico.com/en/documentation/integrate/hosted-checkout-page/) (see the last chapter) and in [the API references](https://support.direct.ingenico.com/en/documentation/api/reference/#tag/HostedCheckout/operation/CreateHostedCheckoutApi).

If anything is still unclear, please contact Direct support at: [https://support.direct.ingenico.com/en/help/contact/](https://support.direct.ingenico.com/en/help/contact/).

Kind regards,
Worldline Direct Support Team
