### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by OlegKunitsyn** [wl-online-payments-direct/sdk-php#5]
Return URL does not redirect customer at step 8 by using
- https://support.direct.ingenico.com/en/documentation/integrate/hosted-checkout-page/
- https://support.direct.ingenico.com/en/documentation/sdk/server/php/

Since June the official customer support is unable to solve the problem: "Leider können wir nicht direkt mit Softwarespezifischen Fragen unterstützen." Any ideas?

**Comment by worldline-direct-support-team** [comment]
Hi @OlegKunitsyn,

The SDK does not handle the redirection so unfortunately we can't give full support on this.
As the official customer support indicates, we can't give support on what happens with the SDK, only what happens in the SDK.

Could you enable logging of the SDK and verify that the response looks a bit like this?
`{
    "RETURNMAC": "99ca2572-0ef3-4b81-8aa6-40eb8bd4f9fb",
    "hostedCheckoutId": "3634132762",
    "merchantReference": "b738cd662f344e6d86f825ea8549ccbe",
    "redirectUrl": "https://payment.direct.ingenico.com/hostedcheckout/PaymentMethods/Selection/0c23****",
    "partialRedirectUrl": "direct.ingenico.com/hostedcheckout/PaymentMethods/Selection/0c23****"
}`

If it does, could you verify you are able to retrieve the URL of the hosted checkout in your code by calling `getPartialRedirectUrl` or `getRedirectUrl` on the response object? If that works, then the SDK works as expected and the rest is up to your platform.

Kind regards,
Wordline Direct support team

**Comment by OlegKunitsyn** [comment]
Issue spotted, thanks. Unfortunately, the documentation https://support.direct.ingenico.com/en/documentation/sdk/server/php/ does not describe ReturnUrl case. Finally, I reproduced necessary source-code using https://support.direct.ingenico.com/en/documentation/integrate/hosted-checkout-page/ as a pattern.
