### ISSUE TITLE
Aliases with Hosted Payments

### ISSUE THREAD

**Issue by OlegKunitsyn** [wl-online-payments-direct/sdk-php#6]
Can you show an Alias creation for Hosted Payment? A unit-test might be sufficient.
Documentation https://support.direct.ingenico.com/en/documentation/integrate/hosted-checkout-page/ tells nothing about but https://epayments-support.ingenico.com/en/integration-solutions/recurring-payments/alias-manager/ promises that.
Thank you!

**Comment by worldline-direct-support-team** [comment]
Hi @OlegKunitsyn, you can find more information about tokenization with Direct on its dedicated page: [https://support.direct.ingenico.com/en/best-practices/recurring-payments/create-token](https://support.direct.ingenico.com/en/best-practices/recurring-payments/create-token).
In short, you can set the 'tokenize' properties of the card & redirect payment method specific inputs of CreateHostedCheckoutRequest to true to ensure the creation of a token in most cases.

Please note that the SDK is not intended as a documentation tool for the many different features of Direct.
Also, the second URL you reference refers to a different product than Direct, and not all of their features are identical.
